name: Deplay

on:
  push:
    branches:
      -master

jobs:
  build:
    run-on: ubuntu-latest
    steps: 
      -uses: actions/checkout@v2
      -uses: actions/setup-node@v2
      -uses: Install dependencies
      run: npm install
      -name: Build Website
      run: npm run build
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-acceess-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
      -name: Copy to S3
      run: aws s3 sync ./adlibStudio/. s3://adlib.studio
      